name: build

on:
    push:
        branches: [main]
        paths:
            - .github/**
            - src/**
            - test/**
            - Makefile
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    SQLITE_RELEASE_YEAR: "2021"
    SQLITE_VERSION: "3360000"
    SQLITE_BRANCH: "3.36"

jobs:
    build:
        name: Build for windows
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - name: Download SQLite sources
              shell: bash
              run: |
                  echo "${PATH//:/$'\n'}"
                  gcc --version
                  which gcc
                  make prepare-dist
                  make download-sqlite
                  make download-external

            - name: Build for Windows
              shell: bash
              run: |
                  make compile-windows
                  make pack-windows

            - name: Upload Windows packages
              uses: actions/upload-artifact@v3
              with:
                name: package
                path: dist/*.zip
